--[[ Genv Table ]]--
getgenv.Drawing
getgenv.Game
getgenv.GetUnlockedModules
getgenv.HttpGet
getgenv.HttpPost
getgenv.Input
getgenv.Instance
getgenv.LockModule
getgenv.OverlapParams
getgenv.Ray
getgenv.RaycastParams
getgenv.Stats
getgenv.UnlockModule
getgenv.UserSettings
getgenv.WebSocket
getgenv.Workspace
getgenv.Xeno
getgenv.about
getgenv.appendfile
getgenv.base64
getgenv.base64_decode
getgenv.base64_encode
getgenv.cache
getgenv.checkcaller
getgenv.checkclosure
getgenv.cleardrawcache
getgenv.clonefunction
getgenv.cloneref
getgenv.compareinstances
getgenv.consoleclear
getgenv.consolecreate
getgenv.consoledestroy
getgenv.consoleerror
getgenv.consoleinfo
getgenv.consoleinput
getgenv.consolename
getgenv.consoleprint
getgenv.consolesettitle
getgenv.consolewarn
getgenv.crypt
getgenv.debug
getgenv.decompile
getgenv.delfile
getgenv.delfolder
getgenv.disassemble
getgenv.dofile
getgenv.dumpstring
getgenv.fireclickdetector
getgenv.fireproximityprompt
getgenv.firetouchinterest
getgenv.game
getgenv.get_hwid
getgenv.getcallingscript
getgenv.getconnections
getgenv.getcustomasset
getgenv.getexecutorname
getgenv.getexecutorversion
getgenv.getfflag
getgenv.getfpscap
getgenv.getfunctions
getgenv.getgc
getgenv.getgenv
getgenv.gethiddenproperties
getgenv.gethiddenproperty
getgenv.gethui
getgenv.gethwid
getgenv.getidentity
getgenv.getinstanceaddress
getgenv.getinstancefunctions
getgenv.getinstances
getgenv.getloadedmodules
getgenv.getnilinstances
getgenv.getproperties
getgenv.getrbxscriptsignals
getgenv.getrbxsignals
getgenv.getrenderproperty
getgenv.getrenv
getgenv.getrunningscripts
getgenv.getscriptbytecode
getgenv.getscriptclosure
getgenv.getscriptfunction
getgenv.getscripthash
getgenv.getscripts
getgenv.getsenv
getgenv.getsimulationradius
getgenv.getthreadcontext
getgenv.getthreadidentity
getgenv.hookfunction
getgenv.hookinstance
getgenv.http
getgenv.http_request
getgenv.identifyexecutor
getgenv.iscclosure
getgenv.isexecutorclosure
getgenv.isfile
getgenv.isfolder
getgenv.isgameactive
getgenv.islclosure
getgenv.isnetworkowner
getgenv.isourclosure
getgenv.isrbxactive
getgenv.isreadonly
getgenv.isrenderobj
getgenv.isscriptable
getgenv.iswindowactive
getgenv.keypress
getgenv.keyrelease
getgenv.listfiles
getgenv.loadfile
getgenv.loadstring
getgenv.lz4compress
getgenv.lz4decompress
getgenv.makefolder
getgenv.mouse1click
getgenv.mouse1press
getgenv.mouse1release
getgenv.mouse2click
getgenv.mouse2press
getgenv.mouse2release
getgenv.mousemoveabs
getgenv.mousemoverel
getgenv.mousescroll
getgenv.newcclosure
getgenv.newlclosure
getgenv.queue_on_teleport
getgenv.queueonteleport
getgenv.rconsoleclear
getgenv.rconsolecreate
getgenv.rconsoledestroy
getgenv.rconsoleerror
getgenv.rconsoleinfo
getgenv.rconsoleinput
getgenv.rconsolename
getgenv.rconsoleprint
getgenv.rconsolesettitle
getgenv.rconsolewarn
getgenv.readfile
getgenv.replaceclosure
getgenv.request
getgenv.require
getgenv.restorescriptbytecode
getgenv.savegame
getgenv.saveinstance
getgenv.setclipboard
getgenv.setfflag
getgenv.setfpscap
getgenv.sethiddenproperty
getgenv.setidentity
getgenv.setrbxclipboard
getgenv.setreadonly
getgenv.setrenderproperty
getgenv.setscriptable
getgenv.setscriptbytecode
getgenv.setsimulationradius
getgenv.setthreadcontext
getgenv.setthreadidentity
getgenv.settings
getgenv.stats
getgenv.toclipboard
getgenv.type
getgenv.typeof
getgenv.whatexecutor
getgenv.workspace
getgenv.writefile
getgenv.writefile_n
